#-*- coding:utf8 -*-
__author__ = 'qiqi'

#MYSQL
SQLALCHEMY_DATABASE_URI = 'mysql://root:123@192.168.66.100:3306/qblog'
SQLALCHEMY_ENCODING = "utf-8"
SQLALCHEMY_ECHO = False
DEBUG = True

SQLALCHEMY_TRACK_MODIFICATIONS = True

#SERVER PORT
SERVER_PORT = 5000

SECRET_KEY = "sdfdsf"